#pragma once

#include <Parsers/graph/AST/GQLAssignmentItem.h>
#include <Parsers/graph/AST/GQLAtSchemaClause.h>
#include <Parsers/graph/AST/GQLBindingInitializer.h>
#include <Parsers/graph/AST/GQLBindingTableExpression.h>
#include <Parsers/graph/AST/GQLBindingVariableDefinition.h>
#include <Parsers/graph/AST/GQLBindingVariableDefinitionBlock.h>
#include <Parsers/graph/AST/GQLCallClauseBase.h>
#include <Parsers/graph/AST/GQLCallInlineClause.h>
#include <Parsers/graph/AST/GQLCallNamedClause.h>
#include <Parsers/graph/AST/GQLCallVariableScopeClause.h>
#include <Parsers/graph/AST/GQLCombinedQuery.h>
#include <Parsers/graph/AST/GQLEdgePattern.h>
#include <Parsers/graph/AST/GQLExpr.h>
#include <Parsers/graph/AST/GQLFinishClause.h>
#include <Parsers/graph/AST/GQLForClause.h>
#include <Parsers/graph/AST/GQLGraphExpression.h>
#include <Parsers/graph/AST/GQLGraphPatternBlock.h>
#include <Parsers/graph/AST/GQLGroupByClause.h>
#include <Parsers/graph/AST/GQLLabelExpression.h>
#include <Parsers/graph/AST/GQLLetClause.h>
#include <Parsers/graph/AST/GQLListConstructor.h>
#include <Parsers/graph/AST/GQLMatchClause.h>
#include <Parsers/graph/AST/GQLMatchStatementBlock.h>
#include <Parsers/graph/AST/GQLNodePattern.h>
#include <Parsers/graph/AST/GQLOrderByClause.h>
#include <Parsers/graph/AST/GQLOrderByItem.h>
#include <Parsers/graph/AST/GQLPageClause.h>
#include <Parsers/graph/AST/GQLParenthesizedPathPattern.h>
#include <Parsers/graph/AST/GQLPathPattern.h>
#include <Parsers/graph/AST/GQLPathPatternPrefix.h>
#include <Parsers/graph/AST/GQLPropertyItem.h>
#include <Parsers/graph/AST/GQLPropertyMap.h>
#include <Parsers/graph/AST/GQLQuantifier.h>
#include <Parsers/graph/AST/GQLRecordConstructor.h>
#include <Parsers/graph/AST/GQLReturnClause.h>
#include <Parsers/graph/AST/GQLSchemaReference.h>
#include <Parsers/graph/AST/GQLSelectClause.h>
#include <Parsers/graph/AST/GQLSelectSourceItem.h>
#include <Parsers/graph/AST/GQLSelectSourceList.h>
#include <Parsers/graph/AST/GQLSingleQuery.h>
#include <Parsers/graph/AST/GQLSubquery.h>
#include <Parsers/graph/AST/GQLSubqueryNextClause.h>
#include <Parsers/graph/AST/GQLUseClause.h>
#include <Parsers/graph/AST/GQLWhereClause.h>
#include <Parsers/graph/AST/GQLYieldClause.h>
