#pragma once

#include <Parsers/graph/AST/GQLClausesQuery.h>
#include <Parsers/graph/AST/GQLAssignmentItem.h>
#include <Parsers/graph/AST/GQLCallClause.h>
#include <Parsers/graph/AST/GQLEdgePattern.h>
#include <Parsers/graph/AST/GQLExpr.h>
#include <Parsers/graph/AST/GQLFinishClause.h>
#include <Parsers/graph/AST/GQLForClause.h>
#include <Parsers/graph/AST/GQLLabelExpression.h>
#include <Parsers/graph/AST/GQLLetClause.h>
#include <Parsers/graph/AST/GQLMatchClause.h>
#include <Parsers/graph/AST/GQLNodePattern.h>
#include <Parsers/graph/AST/GQLOrderByClause.h>
#include <Parsers/graph/AST/GQLOrderByItem.h>
#include <Parsers/graph/AST/GQLPageClause.h>
#include <Parsers/graph/AST/GQLPathPattern.h>
#include <Parsers/graph/AST/GQLProjectClause.h>
#include <Parsers/graph/AST/GQLSelectSourceItem.h>
#include <Parsers/graph/AST/GQLSelectSourceList.h>
#include <Parsers/graph/AST/GQLPropertyItem.h>
#include <Parsers/graph/AST/GQLPropertyMap.h>
#include <Parsers/graph/AST/GQLQuantifier.h>
#include <Parsers/graph/AST/GQLSetQuery.h>
#include <Parsers/graph/AST/GQLWhereClause.h>
